version: '3.8'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql/music_db


volumes:
  mysql_data: